steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['-i -e "s/${_GCP_PROJECT}/$GCP_PROJECT/g"',
  'app.yaml']
  entrypoint: sed
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy',
   '--no-promote',
   '--stop-previous-version',
   '--project', '${_GCP_PROJECT}',
   '--quiet']
